### ISSUE TITLE
Mac OS? More like POO OS!

### ISSUE THREAD

**Issue by duckymomo360** [playi/WonderPy#24]
I was planning to use this because your crappy program doesn't support threads. But oh no no, you think Mac OS is just too good. I can't use this for my class because we use the **superior** Windows OS here

I bet your API Isn't even updated to work with  Mac OS Mojave you silly Mountain Lion nerd.

**Comment by duckida** [comment]
This comment is spam and should be removed

**Comment by duckymomo360** [comment]
> This comment is spam and should be removed

oh, boo hoo.
